# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake

# The command to remove a file.
RM = /home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jennifer/repos/raw2header

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jennifer/repos/raw2header

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/jennifer/st/stm32cubeclt_1.20.0/CMake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jennifer/repos/raw2header/CMakeFiles /home/jennifer/repos/raw2header//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jennifer/repos/raw2header/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raw2header

# Build rule for target.
raw2header: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raw2header
.PHONY : raw2header

# fast build rule for target.
raw2header/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/build
.PHONY : raw2header/fast

#=============================================================================
# Target rules for targets named test_adpcm

# Build rule for target.
test_adpcm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_adpcm
.PHONY : test_adpcm

# fast build rule for target.
test_adpcm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/build
.PHONY : test_adpcm/fast

adpcm.o: adpcm.c.o
.PHONY : adpcm.o

# target to build an object file
adpcm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/adpcm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/adpcm.c.o
.PHONY : adpcm.c.o

adpcm.i: adpcm.c.i
.PHONY : adpcm.i

# target to preprocess a source file
adpcm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/adpcm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/adpcm.c.i
.PHONY : adpcm.c.i

adpcm.s: adpcm.c.s
.PHONY : adpcm.s

# target to generate assembly for a file
adpcm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/adpcm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/adpcm.c.s
.PHONY : adpcm.c.s

raw2header.o: raw2header.c.o
.PHONY : raw2header.o

# target to build an object file
raw2header.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/raw2header.c.o
.PHONY : raw2header.c.o

raw2header.i: raw2header.c.i
.PHONY : raw2header.i

# target to preprocess a source file
raw2header.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/raw2header.c.i
.PHONY : raw2header.c.i

raw2header.s: raw2header.c.s
.PHONY : raw2header.s

# target to generate assembly for a file
raw2header.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raw2header.dir/build.make CMakeFiles/raw2header.dir/raw2header.c.s
.PHONY : raw2header.c.s

test_adpcm.o: test_adpcm.c.o
.PHONY : test_adpcm.o

# target to build an object file
test_adpcm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/test_adpcm.c.o
.PHONY : test_adpcm.c.o

test_adpcm.i: test_adpcm.c.i
.PHONY : test_adpcm.i

# target to preprocess a source file
test_adpcm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/test_adpcm.c.i
.PHONY : test_adpcm.c.i

test_adpcm.s: test_adpcm.c.s
.PHONY : test_adpcm.s

# target to generate assembly for a file
test_adpcm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_adpcm.dir/build.make CMakeFiles/test_adpcm.dir/test_adpcm.c.s
.PHONY : test_adpcm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... raw2header"
	@echo "... test_adpcm"
	@echo "... adpcm.o"
	@echo "... adpcm.i"
	@echo "... adpcm.s"
	@echo "... raw2header.o"
	@echo "... raw2header.i"
	@echo "... raw2header.s"
	@echo "... test_adpcm.o"
	@echo "... test_adpcm.i"
	@echo "... test_adpcm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

